### ISSUE TITLE
einfacheres Demo-Login

### ISSUE THREAD

**Issue by muescha** [Skn0tt/EntE#13]
## einfacheres Passwort

- ich würde für das Passwort in der Demo ein etwas einfacheres Passwort nehmen (zB `demo`, `pw`).

## einfachere Benutzernamen

- auch Benutzernamen evtl einfacher: `schueler`, `lehrer`, `eltern`

## Hilfe im Loginscreen

- evtl ja nen DropDown Feld mit den Nutzern oder
- die Passwort info direkt im LoginScreen anzeigen

## Motivation

die Demo-Seite wird im selben Fenster angezeigt wie die Info-Seite, und man kann man sich die Benutzernamen schlecht merken, somit muss man entweder vor und zurück klicken, oder wissen wie man die Demo Seite in einem neuen Tab öffnet.

**Comment by Skn0tt** [comment]
Danke für dein Feedback! EntE hat Mindestanforderungen an Passwörter, die ich für die Demo nicht einfach mal aushebeln möchte. Die Benutzernamen habe ich extra so gewählt, damit Sie ein wenig menschlischer wirken.

Die Idee, die Demo in einem neuen Tab zu öffnen, ist super, das werde ich sofort umsetzen - und auch die Anzeige der Anmeldedaten auf dem Login-Screen finde ich gut.

**Comment by Skn0tt** [comment]
Ist beides umgesetzt :)

**Comment by muescha** [comment]
dachte die Mindestanforderung für Passwörter werden nur einmal beim Abspeichern/Ändern gesprüft ...
